### ISSUE TITLE
can you please provide some examples?

### ISSUE THREAD

**Issue by Sparo** [tony-o/harmony#1]
I am trying to create system that have one entry point (load balancer ex.harmony + proxy ex. caronte) split trafic to other node servers...

so my question is where to put client and where server (regarding to your initial example)?
I need one port to listen is web/web-socket servers are alive, and based on that to pass traffic on the free, or less loaded server...

I didn't get it from initial example? 
:(

**Comment by tony-o** [comment]
Hi Sparo - are you trying to use this across multiple physical servers?

I've updated the docs with a multi-server example as well.. can you please take a look

**Comment by Sparo** [comment]
yes, that is the idea...

**Comment by Sparo** [comment]
Ok, so I get it now... tnx... :)
but I have one more question... what is port or link that **balance.mydomain** listen... I gess there I have to create server -  or not? Client Servers answers to balancer via`host:"balance.mydomain"` so harmony knows how to balance them, but if balance.mydomain is my entry point, is web access for it `balance.mydomain:????`

and one more :)

if I use WebSockets (socket.io) here, what is with socket session, because sockets have handshake authorization , but if I use multiple servers than socket breaks because of the session changes via balancer...

Sorry if I bother you, but I am looking for solution for my node horizontal scaling on multiple servers and this looks like perfect solution, but still learning about it... 

tnx in advance...
:)

**Comment by tony-o** [comment]
Hi Sparo,

So your balance.mydomain will automatically create the server to listen on whatever port you specify in the `listenport` option of the `harmony.server` initializer.  Your entry point would be balance.mydomain so you'd run the balancer on that server and your clients would connect directly to it (or through a firewall or any other of the "normal" options folks use when building websites).

I never used this for Websockets or even tested it out.  I'd be more than happy to make this solution play well with those if you run into trouble, though.

**Comment by Sparo** [comment]
tnx, a lot... it's much cleaner now...
:+1:

**Comment by tony-o** [comment]
Hi Sparo - curious if you had any luck with Socket.IO.  I should have mentioned that you'd probably need to set persistent to true on the server so it always tries to connect to the same server
