### ISSUE TITLE
add cluster support

### ISSUE THREAD

**Issue by luxor99** [tony-o/harmony#2]
You have an excellend module here.  Would be great if it supported node cluster where multiple worker processes listen on same port.

**Comment by tony-o** [comment]
@luxor99 can you clarify what you mean by multiple worker processes listen on the same port?  They can do that if they are bound to separate physical addresses or on separate hardware.  Otherwise it's like trying to start an Apache server twice, the second one will always error out saying port '80' is in use.

**Comment by luxor99** [comment]
node cluster spawns worker processes that can share the same port.  Please see : http://rowanmanning.com/posts/node-cluster-and-express/

**Comment by tony-o** [comment]
@luxor99 I see, basically what you would do is spawn the cluster/express set up and then use harmony.client to register the express cluster on whatever port the app is listening on.  does that make sense?  

A quick example of what the client side might look like:

``` javascript
var cluster = require('cluster');
var express = require("express");
var harmony = require("node-harmony");

/*
  set up express cluster, taken from your example page
*/

if (cluster.isMaster) {
    var cpuCount = require('os').cpus().length;
    for (var i = 0; i < cpuCount; i += 1) {
        cluster.fork();
    }


    var balanceClient = new harmony.client({
        balance:500 // I'm average at 500 weight
        ,listenport:9000
        ,ack:60*1000
    });
} else {
    var express = require('express');
    var app = express();

    app.get('/', function (req, res) {
        res.send('Hello World!');
    });

    app.listen(3000);
    console.log('Application running!');

}
```

**Comment by tony-o** [comment]
@luxor99 full working example can be found here: https://github.com/tony-o/harmony/blob/master/examples/express_cluster.js

In the example: 
http://localhost:3001/   <- this will hit the express cluster directly..
http://localhost:3000/   <- this will hit the harmony server which will route you to the only express cluster in the file, if you had another cluster running elsewhere then the harmony server becomes unnecessary, you would just point the client on the second cluster to the main harmony server.

Please take a look and let me know if you have more questions -

**Comment by luxor99** [comment]
That is a really nice solution!  The only thing that doesn't seem to work properly for me is persistence.  What I need in my application is a sticky session, so that every request from the same IP, for example, always goes to the same worker.  Harmony by itself works properly in this regard, but when you add node cluster in the mix, it doesn't work, even when option "persistence=true". 

Also, harmony seems to have a dependency on skoconc that's not mentioned.

**Comment by tony-o** [comment]
@luxor99 I've updated the dependencies in the package.json - thank you for pointing that out.  Are you looking for harmony to push the connection to the same express worker every time?  Harmony is only managing connections to the cluster and then that cluster master is managing which worker in the worker pool the picks up the connection.  I don't believe cluster provides a mechanism to push a certain IP to the same worker process every time.  That'd be handled by Express or Cluster, though.  

What are you trying to achieve, are you doing DB connections in each worker process?  If that's the case, check out DB connection pools.

**Comment by luxor99** [comment]
My app uses dynamic routes, so things break if different workers get different requests.  I still haven't found a way to override cluster's lack of persistence.

**Comment by tony-o** [comment]
@luxor99 you might try putting the Harmony.client piece in the worker part of the cluster.  I'd be interested to know if that works or not, I don't know how cluster is managing the port.

The other option is to spawn multiple express instances on different ports and then register those instances with Harmony, that would keep the connections persistent but it's not as clean as using Cluster.
